"""strategy required margin and activation attempts

Revision ID: 0002
Revises: baseline
Create Date: 2026-10-05 17:33:42.709373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel types)


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = 'baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # reviewed by hand: NOT NULL columns need a server default so existing rows survive the upgrade
    with op.batch_alter_table('chaintransfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_margin_usd', sa.Numeric(precision=38, scale=12), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('activation_attempts', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('chaintransfer', schema=None) as batch_op:
        batch_op.drop_column('note')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_column('activation_attempts')
        batch_op.drop_column('required_margin_usd')

    # ### end Alembic commands ###
