"""baseline

Revision ID: baseline
Revises: 
Create Date: 2026-10-05 17:16:55.705159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerate emits sqlmodel types)


# revision identifiers, used by Alembic.
revision: str = 'baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signer_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorization', sa.JSON(), nullable=True),
    sa.Column('record', sa.JSON(), nullable=True),
    sa.Column('hl_order_ids', sa.JSON(), nullable=True),
    sa.Column('solana_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation_sig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('chaintransfer',
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refund_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation_sig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('signature')
    )
    op.create_table('payment',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'seq')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_to'), ['to'], unique=False)

    op.create_table('pnlsnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ts', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('funding_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('fees_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('hedge_pnl_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('margin_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pnlsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pnlsnapshot_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pnlsnapshot_ts'), ['ts'], unique=False)

    op.create_table('schedule',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fund_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('amount_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('memo_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_payments', sa.Integer(), nullable=True),
    sa.Column('end_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('total_paid_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('next_run', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_name'), ['name'], unique=False)

    op.create_table('strategy',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fund_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fund_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hedge_ratio_bps', sa.Integer(), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('rebalance_band_bps', sa.Integer(), nullable=False),
    sa.Column('target_exposure_units', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('return_wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registered_sender_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('multisig', sa.Boolean(), nullable=False),
    sa.Column('expected_amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('received_amount_usd', sa.Numeric(precision=38, scale=12), nullable=True),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('deploy_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('margin_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('size', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('entry_px', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('realized_pnl_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('fees_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('funding_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('funding_cursor_ms', sa.Integer(), nullable=False),
    sa.Column('hl_order_ids', sa.JSON(), nullable=True),
    sa.Column('last_attestation_sig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('deployed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('closed_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intent_id'), ['intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strategy_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_registered_sender_address'), ['registered_sender_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_status'), ['status'], unique=False)

    op.create_table('strategydeposit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('expected_amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('received_amount_usd', sa.Numeric(precision=38, scale=12), nullable=True),
    sa.Column('source_wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registered_sender_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('multisig', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('solana_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategydeposit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategydeposit_intent_id'), ['intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strategydeposit_registered_sender_address'), ['registered_sender_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategydeposit_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategydeposit_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('usednonce',
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    with op.batch_alter_table('usednonce', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usednonce_created_at'), ['created_at'], unique=False)

    op.create_table('watchercursor',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('withdrawal',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=38, scale=12), nullable=False),
    sa.Column('destination_wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('solana_signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attestation_sig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_auth_nonce'), ['auth_nonce'], unique=True)
        batch_op.create_index(batch_op.f('ix_withdrawal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_strategy_id'), ['strategy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_status'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_auth_nonce'))

    op.drop_table('withdrawal')
    op.drop_table('watchercursor')
    with op.batch_alter_table('usednonce', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usednonce_created_at'))

    op.drop_table('usednonce')
    with op.batch_alter_table('strategydeposit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategydeposit_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategydeposit_status'))
        batch_op.drop_index(batch_op.f('ix_strategydeposit_registered_sender_address'))
        batch_op.drop_index(batch_op.f('ix_strategydeposit_intent_id'))

    op.drop_table('strategydeposit')
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_registered_sender_address'))
        batch_op.drop_index(batch_op.f('ix_strategy_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_org_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_intent_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_fund_id'))

    op.drop_table('strategy')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_name'))

    op.drop_table('schedule')
    with op.batch_alter_table('pnlsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pnlsnapshot_ts'))
        batch_op.drop_index(batch_op.f('ix_pnlsnapshot_strategy_id'))

    op.drop_table('pnlsnapshot')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_to'))
        batch_op.drop_index(batch_op.f('ix_payment_schedule_id'))

    op.drop_table('payment')
    op.drop_table('chaintransfer')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_action_created_at'))

    op.drop_table('action')
    # ### end Alembic commands ###
